//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Instaclone.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feed
    {
        public Feed()
        {
            this.Comment = new HashSet<Comment>();
        }
    
        public int FeedID { get; set; }
        public string Username { get; set; }
        public string ImageURL { get; set; }
        public int Likes { get; set; }
    
        public virtual ICollection<Comment> Comment { get; set; }
    }
}
